# Generated by Django 4.2.6 on 2023-10-23 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Salespeople",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.IntegerField(unique=True)),
                ("photo", models.FileField(upload_to="")),
                (
                    "main_region",
                    models.IntegerField(
                        choices=[
                            (0, "Southern Region"),
                            (1, "Coastal Region"),
                            (2, "Northern Region"),
                            (3, "Eastern Region"),
                            (4, "Lebanon Region"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("south_sales", models.DecimalField(decimal_places=3, max_digits=15)),
                ("coast_sales", models.DecimalField(decimal_places=3, max_digits=15)),
                ("north_sales", models.DecimalField(decimal_places=3, max_digits=15)),
                ("east_sales", models.DecimalField(decimal_places=3, max_digits=15)),
                ("lebanon_sales", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "total_commission",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1),
                            django.core.validators.MaxValueValidator(limit_value=12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=2000),
                            django.core.validators.MaxValueValidator(limit_value=2100),
                        ]
                    ),
                ),
                (
                    "sales_people",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salesapp.salespeople",
                    ),
                ),
            ],
        ),
    ]
