# Generated by Django 4.2.6 on 2023-10-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commissionrate',
            unique_together={('sales_people', 'month', 'year')},
        ),
    ]
